name: sestavr
version: 0.1.0.0
github: "jhrcek/sestavr"
license: BSD3
author: "Jan Hrček"
maintainer: "example@example.com"
copyright: "2020 Jan Hrček"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/jhrcek/sestavr#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - conduit
  - file-embed
  - http-media
  - monad-logger
  - persistent
  - persistent-template
  - persistent-sqlite
  - servant
  - servant-server
  - text
  - time
  - wai
  - warp
ghc-options:
 - -Wall

library:
  source-dirs: src

executables:
  sestavr-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sestavr

tests:
  sestavr-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sestavr
